<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ThreadSeeder extends Seeder
{
    public function run()
    {
        DB::table('threads')->insert([
            [
                'slug' => 'thread 1',
                'user_id' => 1,
                'channel_id' => 1,
                'replies_count' => 0,
                'title' => 'Thread 1',
                'body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 2',
                'user_id' => 1,
                'channel_id' => 1,
                'replies_count' => 0,
                'title' => 'Thread 2',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 3',
                'user_id' => 1,
                'channel_id' => 2,
                'replies_count' => 0,
                'title' => 'Thread 3',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 4',
                'user_id' => 1,
                'channel_id' => 2,
                'replies_count' => 0,
                'title' => 'Thread 4',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 5',
                'user_id' => 1,
                'channel_id' => 1,
                'replies_count' => 1,
                'title' => 'Thread 5',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 6',
                'user_id' => 1,
                'channel_id' => 1,
                'replies_count' => 1,
                'title' => 'Thread 6',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 7',
                'user_id' => 1,
                'channel_id' => 2,
                'replies_count' => 1,
                'title' => 'Thread 7',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 8',
                'user_id' => 1,
                'channel_id' => 2,
                'replies_count' => 1,
                'title' => 'Thread 8',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 9',
                'user_id' => 2,
                'channel_id' => 1,
                'replies_count' => 0,
                'title' => 'Thread 9',
                'body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 10',
                'user_id' => 2,
                'channel_id' => 1,
                'replies_count' => 0,
                'title' => 'Thread 10',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 11',
                'user_id' => 2,
                'channel_id' => 2,
                'replies_count' => 0,
                'title' => 'Thread 11',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 12',
                'user_id' => 2,
                'channel_id' => 2,
                'replies_count' => 0,
                'title' => 'Thread 12',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 13',
                'user_id' => 2,
                'channel_id' => 1,
                'replies_count' => 1,
                'title' => 'Thread 13',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 14',
                'user_id' => 2,
                'channel_id' => 1,
                'replies_count' => 1,
                'title' => 'Thread 14',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread 15',
                'user_id' => 2,
                'channel_id' => 2,
                'replies_count' => 1,
                'title' => 'Thread 15',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread-16',
                'user_id' => 2,
                'channel_id' => 2,
                'replies_count' => 1,
                'title' => 'Thread 16',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread-17',
                'user_id' => 3,
                'channel_id' => 1,
                'replies_count' => 1,
                'title' => 'Thread 17',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread-18',
                'user_id' => 4,
                'channel_id' => 1,
                'replies_count' => 1,
                'title' => 'Thread 18',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread-19',
                'user_id' => 5,
                'channel_id' => 1,
                'replies_count' => 1,
                'title' => 'Thread 19',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread-20',
                'user_id' => 6,
                'channel_id' => 1,
                'replies_count' => 1,
                'title' => 'Thread 20',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread-21',
                'user_id' => 7,
                'channel_id' => 1,
                'replies_count' => 1,
                'title' => 'Thread 21',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread-22',
                'user_id' => 8,
                'channel_id' => 1,
                'replies_count' => 1,
                'title' => 'Thread 22',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread-23',
                'user_id' => 3,
                'channel_id' => 2,
                'replies_count' => 1,
                'title' => 'Thread 23',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread-24',
                'user_id' => 4,
                'channel_id' => 2,
                'replies_count' => 1,
                'title' => 'Thread 24',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread-25',
                'user_id' => 5,
                'channel_id' => 2,
                'replies_count' => 1,
                'title' => 'Thread 25',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread-26',
                'user_id' => 6,
                'channel_id' => 2,
                'replies_count' => 1,
                'title' => 'Thread 26',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread-27',
                'user_id' => 7,
                'channel_id' => 2,
                'replies_count' => 1,
                'title' => 'Thread 27',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
            [
                'slug' => 'thread-28',
                'user_id' => 8,
                'channel_id' => 2,
                'replies_count' => 1,
                'title' => 'Thread 28',
                'body' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.',
                'best_reply_id' => null,
            ],
        ]);
    }
}
